# Generated by Django 4.2.3 on 2023-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='B', max_length=1),
        ),
    ]
