# Generated by Django 4.2.3 on 2023-07-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_animal_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='kind',
        ),
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='content.kind'),
        ),
    ]
