# Generated by Django 4.2.3 on 2023-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_animal_kind_animal_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='old',
            field=models.IntegerField(default=1),
        ),
    ]
